- name: install EPEL 
  yum:
    name: epel-release
    state: present

- name: install Podman
  yum:
    name: podman
    state: present

- name: service is started
  service:
    name: podman
    state: started
    enabled: yes

- name: directory HAProxy config
  file:
    path: /etc/haproxy
    state: directory

- name: Deploy HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: HAProxy container
  command: >
    podman run -d --name haproxy
    -v /etc/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    -p 80:80
    haproxy:latest
  when: inventory_hostname == "soufe1"

- name: Create directory for containers volumes
  file:
    path: /containers_vols
    state: directory
    mode: '0755'

- name: Create Prometheus data directory
  file:
    path: /containers_vols/prometheus/data
    state: directory
    owner: "{{ prometheus_id }}"
    group: "{{ prometheus_id }}"
    mode: '0755'

- name: Deploy Prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: /containers_vols/prometheus/config/prometheus.yml

- name: Run Prometheus container
  command: >
    podman run -d --name prometheus
    -v /containers_vols/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:z
    -v /containers_vols/prometheus/data:/prometheus:z
    -p 9090:9090
    prom/prometheus:{{ prometheus_tag }}
  when: inventory_hostname == "soube2"

- name: Create Grafana data directory
  file:
    path: /containers_vols/grafana/data
    state: directory
    owner: "{{ grafana_id }}"
    group: "{{ grafana_id }}"
    mode: '0755'
n
- name: Deploy Grafana configuration
  template:
    src: grafana.ini.j2
    dest: /containers_vols/grafana/config/grafana.ini

- name: Run Grafana container
  command: >
    podman run -d --name grafana
    -v /containers_vols/grafana/config/grafana.ini:/etc/grafana/grafana.ini:z
    -v /containers_vols/grafana/data:/var/lib/grafana:z
    -p 3000:3000
    grafana/grafana
  when: inventory_hostname == "soube2"
